# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(default='...', max_length=10, verbose_name='Symbol')),
                ('coinmarketcap_com_id', models.CharField(default='...', max_length=25, verbose_name='Symbol or id in coinmarketcap_com API')),
                ('price_btc', models.DecimalField(decimal_places=30, default=0, max_digits=40)),
                ('price_usd', models.DecimalField(decimal_places=30, default=0, max_digits=40)),
                ('capitalization', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('market_supply', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('total_supply', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('price_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinmarket.Coin')),
            ],
        ),
    ]
