# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'Coin', 'verbose_name_plural': 'Coins'},
        ),
        migrations.AlterModelOptions(
            name='coinportfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='coinportfolioentry',
            options={'verbose_name': 'Portfolio Entry', 'verbose_name_plural': 'Portfolio Entries'},
        ),
        migrations.AlterField(
            model_name='coin',
            name='blockchain',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cryptocoins.Coin'),
        ),
    ]
