# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='last_update_try',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coin',
            name='blockchain',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='coinmarket.Coin'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
