# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coinmarket', '0002_auto_20170624_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('balance_usd', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('balance_euros', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_address', models.CharField(max_length=50, verbose_name='Public Key')),
                ('balance', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('buy_price_usd', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('balance_usd', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('profit', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinmarket.Coin')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='coinmarket.CoinPortfolio')),
            ],
        ),
    ]
