# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinportfolioentry',
            name='public_address',
        ),
        migrations.AddField(
            model_name='coinportfolioentry',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cryptocoins.Address'),
        ),
    ]
