# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0004_auto_20171028_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='public_address',
            field=models.CharField(default='x', max_length=150, verbose_name='Public Key'),
            preserve_default=False,
        ),
    ]
