# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarket', '0004_auto_20170625_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinPortfolioEntries',
            new_name='CoinPortfolioEntry',
        ),
    ]
