# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0005_address_public_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1500, verbose_name='Description')),
                ('type_tr', models.IntegerField(choices=[(1, 'Input'), (2, 'Output'), (3, 'Payment/Income'), (4, 'Cost/Expenses'), (5, 'Exchange Sell'), (6, 'Exchange Buy')])),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('amount_usd', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('entry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cryptocoins.CoinPortfolioEntry')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cryptocoins.CoinPortfolio')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
