# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0006_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount_usd',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_usd_DoT',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40, verbose_name='Amount USD DoT'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processed',
            field=models.IntegerField(default=0, verbose_name='Processed'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_tr',
            field=models.IntegerField(choices=[(1, 'Input'), (2, 'Output'), (3, 'Payment/Income'), (4, 'Cost/Expenses'), (5, 'Exchange Sell'), (6, 'Exchange Buy')], verbose_name='Type'),
        ),
    ]
