# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarket', '0006_auto_20170625_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinportfolio',
            name='cost_usd',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
    ]
