# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarket', '0007_coinportfolio_cost_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('balance_usd', models.DecimalField(decimal_places=10, default=0, max_digits=40)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinmarket.Coin')),
            ],
        ),
    ]
