# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-30 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0007_auto_20171029_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinportfolio',
            old_name='cost_usd',
            new_name='invested_usd',
        ),
        migrations.AddField(
            model_name='coinportfolio',
            name='cash_outs_usd',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
    ]
