# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarket', '0008_balance_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance_new',
            name='coin',
        ),
        migrations.DeleteModel(
            name='Balance_new',
        ),
    ]
