# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarket', '0009_auto_20170629_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(default='...', max_length=30, verbose_name='Symbol'),
        ),
    ]
